### ISSUE TITLE
Crash when converting geneshuffler_0 to scml

### ISSUE THREAD

**Issue by skairunner** [skairunner/kanimal-SE#8]
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'electric_bolt_b_bloom_1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at kanimal.ScmlWriter.AddTimelineInfo(XmlElement parent, Int32 animIndex) in C:\KSE\kanimal\Writer\ScmlWriter.cs:line 200
   at kanimal.ScmlWriter.AddAnimInfo() in C:\KSE\kanimal\Writer\ScmlWriter.cs:line 108
   at kanimal.ScmlWriter.Save(String path) in C:\KSE\kanimal\Writer\ScmlWriter.cs:line 39
   at kanimal.Kanimal.ToScml(String imgPathStr, String buildPathStr, String animPathStr, String outputDir) in C:\KSE\kanimal\kanimAL.cs:line 31
   at kanimal_cli.Program.<>c.<Main>b__2_0(KanimToScmlOptions o) in C:\KSE\kanimal-cli\Program.cs:line 61
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at kanimal_cli.Program.Main(String[] args) in C:\KSE\kanimal-cli\Program.cs:line 46```

kparser original works fine.

**Comment by daviscook477** [comment]
Yeah this was fixed by the last PR, right?

**Comment by daviscook477** [comment]
Resolved with https://github.com/skairunner/kanimal-SE/pull/10
